main: net.nifheim.yitan.itemlorestats.Main
name: ItemLoreStats
version: ${project.version}
author: LoncoCraft
website: noweb
description: 
softdepend: [WorldGuard, Vault, Citizens, ArmorWeight, MVdWPlaceholderAPI, TitleManager]
commands:
  ils:
    description: The core ILS command.
permissions:
  ils.admin: 
    description: Player/group is granted admin privilege.
    default: op
  ils.repair:
    description: Allows players to use the /ils repair command.
    default: op
  ils.commandlist:
    description: Allows players to use the /ils command to view the available ils commands.
    default: op