main: com.github.supavitax.itemlorestats.ItemLoreStats
name: LoncoItemLoreStats
version: 1.0.0
author: LoncoCraft
website: 
description: 
softdepend: [WorldGuard, Vault, Heroes, BarAPI, BossBarAPI, SkillAPI, Citizens, ArmorWeight,MVdWPlaceholderAPI]

commands:
  ils:
    description: The core ILS command.
  clearhand:
    description: The core ILS command.

permissions:
  ils.admin: 
    description: Player/group is granted admin privilege.
    default: op
  ils.repair:
    description: Allows players to use the /ils repair command.
    default: op
  ils.commandlist:
    description: Allows players to use the /ils command to view the available ils commands.
    default: op